"""Deterministic stub AI provider for RAWRS testing.

Returns structured fake results without loading any model. Used when
RAWRS_AI_STUB is set (all unit and API tests) or when no real provider
is available and the caller needs a graceful non-error response.

The stub is NOT the same as an error path. When available=True and
RAWRS_AI_STUB is set, the stub acts as a fully functional provider that
happens to return predictable fake data. This lets tests exercise the
entire generate_alt_text() code path including quality evaluation and
retry logic without a real model.
"""

from pathlib import Path

from src.ai.provider import AICapability, AIProvider


class StubProvider(AIProvider):
    """Deterministic provider for tests and development without a GPU."""

    @property
    def name(self) -> str:
        return "Stub"

    def capabilities(self) -> AICapability:
        return AICapability(
            vision=True,
            max_image_size_px=0,
            available=True,
            model_id="stub",
        )

    def generate_alt_text(self, request: "AltTextRequest") -> "AltTextResult":
        from src.ai.alt_text_generator import AltTextResult

        stem = Path(request.image_path).stem
        return AltTextResult(
            image_type="PHOTOGRAPH",
            description=(
                f"Stub description for image {stem} on page {request.page_number}. "
                "This is a deterministic placeholder generated by the stub provider."
            ),
            purpose="Stub purpose — no real model inference performed (RAWRS_AI_STUB mode).",
            visible_text="None",
            confidence=0.5,
            warnings=["RAWRS_AI_STUB mode — not a real model response"],
        )
